
spring:

  profiles:
    active: ${ACTIVE_PROFILE:dev}

  application:
    name: VisualProgrammingBackend

  jpa:
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC+3
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

  jackson:
    property-naming-strategy: SNAKE_CASE

application:

  security:
    jwt:
      expiration: ${AUTH_EXP_SEC:43200000} # def: half a day => 12 * 60 * 60 * 1000
      refresh-token:
        expiration: ${REFRESH_EXP_SEC:302400000} # def: 7 days

  cors:
    allowed-methods: >
      GET,
      POST,
      PUT,
      DELETE
    allowed-headers: >
      *

springdoc:
  swagger-ui:
    path: /v3/api-docs
  api-docs:
    enabled: false

server:
  port: ${PORT:8080}